git checkout -- web-app/plugins/charts/flot/jquery.flot.grow.js
git checkout -- web-app/plugins/charts/flot/jquery.flot.js
git checkout -- web-app/plugins/charts/flot/jquery.flot.orderBars.js
git checkout -- web-app/plugins/charts/flot/jquery.flot.pie.js
git checkout -- web-app/plugins/charts/flot/jquery.flot.resize.js
git checkout -- web-app/plugins/charts/flot/jquery.flot.tooltip_0.4.4.js
git checkout -- web-app/plugins/charts/knob/jquery.knob.js
git checkout -- web-app/plugins/charts/sparkline/jquery.sparkline.min.js
git checkout -- web-app/plugins/forms/placeholder/jquery.placeholder.min.js
git checkout -- web-app/plugins/forms/uniform/jquery.uniform.min.js
git checkout -- web-app/plugins/forms/uniform/uniform.default.css
git checkout -- web-app/plugins/jquery.mousewheel.js
git checkout -- web-app/plugins/jquery.placeholder.min.js
git checkout -- web-app/plugins/jquery.qtip.min.js
git checkout -- web-app/plugins/misc/fullcalendar/fullcalendar.css
git checkout -- web-app/plugins/misc/fullcalendar/fullcalendar.min.js
git checkout -- web-app/plugins/misc/qtip/jquery.qtip.css
git checkout -- web-app/plugins/misc/qtip/jquery.qtip.min.js
git checkout -- web-app/plugins/misc/search/tipuesearch.css
git checkout -- web-app/plugins/misc/search/tipuesearch.js
git checkout -- web-app/plugins/misc/search/tipuesearch_data.js
git checkout -- web-app/plugins/misc/search/tipuesearch_set.js
git checkout -- web-app/plugins/misc/totop/jquery.ui.totop.min.js
git checkout -- web-app/plugins/tables/dataTables/TableTools.css
git checkout -- web-app/plugins/tables/dataTables/TableTools.min.js
git checkout -- web-app/plugins/tables/dataTables/jquery.dataTables.css
git checkout -- web-app/plugins/tables/dataTables/jquery.dataTables.js
git checkout -- web-app/plugins/tables/dataTables/jquery.dataTables.min.js
