package ar.com.burucps.sales.statement;

import ar.com.burudos.party.Employee;

import ar.com.burudos.sales.statement.Parameter;
import ar.com.burudos.sales.statement.EmployeeStatement;

import ar.com.burudos.sales.Summary;

import ar.com.burucps.sales.statement.StatementLineGroup;
import ar.com.burucps.sales.statement.StatementLineType;

global ar.com.burudos.sales.statement.EmployeeStatement statement
global java.util.Map additionalValues

dialect "mvel"

/* ********************** PUNTOS *********************** */
rule "Puntos - Altas IEM"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "IEM_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_IEM_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 10);
end

rule "Puntos - Bajas IEM"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "IEM_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_IEM_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
			$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 11);
end

rule "Puntos - Altas Cambios de Plan"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CPLAN_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_CPLAN_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 20);
end

rule "Puntos - Bajas Cambios de Plan"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CPLAN_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_CPLAN_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 21);
end

rule "Puntos - Altas Paquetes de Servicio"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "SVC_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_SVC_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 30);
end

rule "Puntos - Bajas Paquetes de Servicio"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "SVC_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_SVC_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 31);
end

rule "Puntos - Altas Garantias"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "GTIA_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_GTIA_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 40);
end

rule "Puntos - Bajas Garantias"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "GTIA_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_GTIA_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 41);
end

rule "Puntos - Altas Migraciones Positivas"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "MIG_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_MIGPOS_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 50);
end

rule "Puntos - Bajas Migraciones Positivas"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "MIG_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_MIGPOS_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 51);
end

rule "Puntos - Altas CATER Pospago"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CATER_POS_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_CATERPOS_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 60);
end

rule "Puntos - Bajas CATER Pospago"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CATER_POS_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_CATERPOS_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 61);
end

rule "Puntos - Altas CATER Prepago"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CATER_PRE_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_CATERPRE_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 70);
end

rule "Puntos - Bajas CATER Prepago"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CATER_PRE_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_CATERPRE_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 71);
end

rule "Puntos - Altas CASIM Pospago"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CASIM_POS_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_CASIMPOS_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 80);
end

rule "Puntos - Bajas CASIM Pospago"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CASIM_POS_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_CASIMPOS_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 81);
end

rule "Puntos - Altas CASIM Prepago"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CASIM_PRE_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_CASIMPRE_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 90);
end

rule "Puntos - Bajas CASIM Prepago"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "CASIM_PRE_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_CASIMPRE_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 91);
end

rule "Puntos - Altas Bonos"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "BONOS_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_BONOS_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 100);
end

rule "Puntos - Bajas Bonos"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "BONOS_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_BONOS_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 101);
end

rule "Puntos - Altas Movitalk"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "MTALK_ALTAS")
	$p : Parameter(paramCode == "PUNTOS_ALTAS_MT_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 110);
end

rule "Puntos - Bajas Movitalk"
salience 99
when
	$empleado : Employee()
	$total : Summary(bu == $empleado.bu && summaryCode == "MTALK_BAJAS")
	$p : Parameter(paramCode == "PUNTOS_BAJAS_MT_PU_PTS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 111);
end

/* ****************** TOTAL PUNTOS ********************* */
rule "Puntos - Totalizacion de puntos"
	salience 95
	when
		$empleado: Employee()
		$pPuntajeObjetivo : Parameter(paramCode == "PTOVTA_OBJ_PTS")
		$pPorcentajePuntajeObjetivoMinimo : Parameter(paramCode == "VTA_CTE_OBJ_PCT")
	then
		statement.addLine(StatementLineType.OBJECTIVE, StatementLineGroup.OBJ_POINTS, $pPuntajeObjetivo.getCurrentDescription(), 
				$pPuntajeObjetivo.getValue(), null, null, 1);
		
		Double total = statement.getPointsSubtotal();
		Double porcentajeAlcanzado = (total / $pPuntajeObjetivo.getValue()) * 100.0;
		statement.setPointsObjPerc(porcentajeAlcanzado);
		Integer factor = 1;
		if (porcentajeAlcanzado < $pPorcentajePuntajeObjetivoMinimo.getValue()) {
			factor = 0;
		}
		additionalValues.put("factorAltas",factor);
		additionalValues.put("IM_PREP",0);
		additionalValues.put("LEC",0);
		additionalValues.put("ALTASVOZ",0);
		additionalValues.put("ALTAS",0);
end

rule "Puntos - Premio Postventa"
salience 94
when
	$empleado: Employee()
	$pPuntajeObjetivo : Parameter(paramCode == "PTOVTA_OBJ_PTS")
	$p : Parameter(paramCode == "PVTA_BON_ARS")
then
	Integer factor = 1;
	if (statement.getPointsObjPerc() < $p.getMinValue()) {
		factor = 0;
	}
	statement.addLine(StatementLineType.RULE, StatementLineGroup.OBJ_POINTS, $p.getCurrentDescription(), 
			$p.getValue(), null, $p.getValue() * factor, 2);
end
/* ******************** FIN PUNTOS ********************* */
/* ********************** ALTAS ************************ */

rule "Altas - IM Control 500 MB"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "IM")
		$p : Parameter(paramCode == "VTA_IM_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 10);
		
		Integer partial = (Integer) additionalValues.get("IM_PREP");
		partial += $total.getQuantity();
		additionalValues.put("IM_PREP", partial);
end

rule "Altas - LEC"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "LEC")
		$p : Parameter(paramCode == "VTA_LEC_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 20);
		additionalValues.put("LEC",$total.getQuantity());
end

rule "Altas - Planes Externo/Interno Rango 1"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "PLAN1")
		$p : Parameter(paramCode == "VTA_PLA_RG1_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 30);
		
		Integer partial = (Integer) additionalValues.get("ALTASVOZ");
		partial += $total.getQuantity();
		additionalValues.put("ALTASVOZ", partial);
end

rule "Altas - Planes Externo/Interno Rango 2"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "PLAN2")
		$p : Parameter(paramCode == "VTA_PLA_RG2_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 31);
		
		Integer partial = (Integer) additionalValues.get("ALTASVOZ");
		partial += $total.getQuantity();
		additionalValues.put("ALTASVOZ", partial);
end

rule "Altas - Planes Externo/Interno Rango 3"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "PLAN3")
		$p : Parameter(paramCode == "VTA_PLA_RG3_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 32);
		
		Integer partial = (Integer) additionalValues.get("ALTASVOZ");
		partial += $total.getQuantity();
		additionalValues.put("ALTASVOZ", partial);
end

rule "Altas - Planes Externo/Interno Rango 4"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "PLAN4")
		$p : Parameter(paramCode == "VTA_PLA_RG4_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 33);
		
		Integer partial = (Integer) additionalValues.get("ALTASVOZ");
		partial += $total.getQuantity();
		additionalValues.put("ALTASVOZ", partial);
end

rule "Altas - Planes Externo/Interno Rango 5"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "PLAN5")
		$p : Parameter(paramCode == "VTA_PLA_RG5_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 34);
		
		Integer partial = (Integer) additionalValues.get("ALTASVOZ");
		partial += $total.getQuantity();
		additionalValues.put("ALTASVOZ", partial);
end

rule "Altas - Planes Corporativos"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "CORP")
		$p : Parameter(paramCode == "VTA_PLA_CORP_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 40);
		
		Integer partial = (Integer) additionalValues.get("ALTASVOZ");
		partial += $total.getQuantity();
		additionalValues.put("ALTASVOZ", partial);
end

rule "Altas - Planes Promo 2x1 2º Linea $ 169"
salience 90
when
	$empleado : Employee()
	$total : Summary(employee == $empleado && summaryCode == "2X1")
	$p : Parameter(paramCode == "VTA_PLA_2X1_PU_ARS")
then
	Integer factor = 1; 
	if (additionalValues.containsKey("factorAltas")) {
		factor = (Integer) additionalValues.get("factorAltas");
	}
	
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 40);
	
	Integer partial = (Integer) additionalValues.get("ALTASVOZ");
	partial += $total.getQuantity();
	additionalValues.put("ALTASVOZ", partial);
end

rule "Altas - Accesorios"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "ACC")
		$p : Parameter(paramCode == "VTA_ACC_BON_PCT")
	then
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() / 100.0, 50);
end

rule "Altas - Prepago Interno"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "PREP")
		$p : Parameter(paramCode == "VTA_PREP_INT_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 60);
		
		Integer partial = (Integer) additionalValues.get("IM_PREP");
		partial += $total.getQuantity();
		additionalValues.put("IM_PREP", partial);
end

rule "Altas - Operaciones Call Center"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "CALL")
		$p : Parameter(paramCode == "VTA_CALL_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 70);
end

rule "Altas - Operaciones Terreno"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "TERR")
		$p : Parameter(paramCode == "VTA_TERR_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 75);
end

rule "Altas - Tarjeta Itau Rango 1 (..10)"
	salience 90
	when
		$empleado : Employee()
		$p : Parameter(paramCode == "VTA_ITAU_RG1_PU_ARS")
		$total : Summary(employee == $empleado && summaryCode == "ITAU" && quantity <= $p.maxValue)
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 80);
end

rule "Altas - Tarjeta Itau Rango 2 (10-20)"
	salience 90
	when
		$empleado : Employee()
		$p : Parameter(paramCode == "VTA_ITAU_RG2_PU_ARS")
		$total : Summary(employee == $empleado && summaryCode == "ITAU" && quantity >= $p.minValue && quantity <= $p.maxValue)
	then
		Integer factor = (Integer) additionalValues.get("factorAltas");Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 81);
end

rule "Altas - Tarjeta Itau Rango 3 (20..)"
	salience 90
	when
		$empleado : Employee()
		$p : Parameter(paramCode == "VTA_ITAU_RG3_PU_ARS")
		$total : Summary(employee == $empleado && summaryCode == "ITAU" && quantity >= $p.minValue)
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 82);
end

rule "Altas - Portabilidades"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "PORT")
		$p : Parameter(paramCode == "VTA_PORT_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 90);
end

rule "Altas - Casim /Repros ($ 50)"
	salience 90
	when
		$empleado : Employee()
		$total : Summary(employee == $empleado && summaryCode == "CASIM_REPRO")
		$p : Parameter(paramCode == "VTA_CASIMREPRO_PU_ARS")
	then
		Integer factor = 1; 
		if (additionalValues.containsKey("factorAltas")) {
			factor = (Integer) additionalValues.get("factorAltas");
		}
		
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity() * factor, 99);
end
/* ******************* TOTAL ALTAS ********************* */
rule "Totalizacion por desempeno individual"
salience 85
when
	$empleado: Employee()
	$pIM : Parameter(paramCode == "QVTA_IM_OP")
	$pLEC : Parameter(paramCode == "QVTA_LEC_OP")
	$pVOZ : Parameter(paramCode == "QVTA_ALTAS_VOZ_OP")
then
	Integer im = (Integer) additionalValues.get("IM_PREP");
	Integer lec = (Integer) additionalValues.get("LEC");
	Integer altasvoz = (Integer) additionalValues.get("ALTASVOZ");
	Integer altas = im + lec + altasvoz;
	Double qAltas = $pIM.getValue() + $pLEC.getValue() + $pVOZ.getValue();
	Integer employeeCount = $empleado.getBu().getEmployeeCount();
	
	additionalValues.put("ALTAS", altas);
	additionalValues.put("QVTA_ALTAS", qAltas);
	
	/* El subtotal upfront se calcula a medida que se agregan lineas.
	 * El total de altas de voz hay que ir calculandolo en cada regla
	 * El total de altas hay que sumar el de altas de voz + IM + LEC */
	
	statement.addLine(StatementLineType.OBJECTIVE, StatementLineGroup.OBJ_Q, $pIM.getCurrentDescription(), 
			$pIM.getValue(), $pIM.getValue() / employeeCount, im, 1);
	statement.addLine(StatementLineType.OBJECTIVE, StatementLineGroup.OBJ_Q, $pLEC.getCurrentDescription(), 
			$pLEC.getValue(), $pLEC.getValue() / employeeCount, lec, 2);
	statement.addLine(StatementLineType.OBJECTIVE, StatementLineGroup.OBJ_Q, $pVOZ.getCurrentDescription(), 
			$pVOZ.getValue(), $pVOZ.getValue() / employeeCount, altasvoz, 3);
	statement.addLine(StatementLineType.OBJECTIVE, StatementLineGroup.OBJ_Q, "Total ALTAS (ALTAS DE VOZ / LEC / PREPAGOS / IM)", 
			qAltas, qAltas / employeeCount, altas, 4);
	
end
/* ******************** FIN ALTAS ********************** */

/* ************** INCENTIVOS INDIVIDUALES ************** */
rule "Incentivos  Individuales - Altas 100% Q"
salience 80
when
	$empleado : Employee()
	$p : Parameter(paramCode == "QVTA_TOT_RG1_BON_ARS")
then
	Integer qAltas = (Integer) additionalValues.get("QVTA_ALTAS");
	Integer altas = (Integer) additionalValues.get("ALTAS");
	Double performance = altas * 100.0 / (qAltas / $empleado.getBu().getEmployeeCount());
	if ( (performance >= $p.getMinValue()) && (performance < $p.getMaxValue())) {
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
					null, null, $p.getValue(), 10);
	}
end

rule "Incentivos  Individuales - Altas 120% Q"
salience 80
when
	$empleado : Employee()
	$p : Parameter(paramCode == "QVTA_TOT_RG2_BON_ARS")
then
	Integer qAltas = (Integer) additionalValues.get("QVTA_ALTAS");
	Integer altas = (Integer) additionalValues.get("ALTAS");
	Double performance = altas * 100.0 / (qAltas / $empleado.getBu().getEmployeeCount());
	if (performance >= $p.getMinValue()) {
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				null, null, $p.getValue(), 11);
	}
end

rule "Incentivos  Individuales - LEC 100% Q"
salience 80
when
	$empleado : Employee()
	$total : Summary(employee == $empleado && summaryCode == "LEC")
	$p : Parameter(paramCode == "QIND_LEC_PU_ARS")
	$q : Parameter(paramCode == "QVTA_LEC_OP")
then
	Double performance = $total.getQuantity() * 100.0 / ($q.getValue() / $empleado.getBu().getEmployeeCount());
	if (performance >= $p.getMinValue()) {
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 20);
	}
end

// TODO
rule "Incentivos  Individuales - Altas de Voz 100% Q"
salience 80
when
	$empleado : Employee()
	$qBu : Parameter(paramCode == "QVTA_ALTAS_VOZ_OP")
	$total : Summary(employee == $empleado && summaryCode == "ALTAS_VOZ")
	$totalBu : Summary(bu == $empleado.bu && summaryCode == "ALTAS_VOZ" && quantity < $qBu.value)
	$p : Parameter(paramCode == "QIND_ALTAS_VOZ_PU_ARS")
then
	Double performance = $total.getQuantity() * 100.0 / ($qBu.getValue() / $empleado.getBu().getEmployeeCount());
	if (performance >= $p.getMinValue()) {
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 30);
	}
end

//TODO
rule "Incentivos  Individuales - Altas de Voz 100% Q y Q Punto de Venta"
salience 80
when
	$empleado : Employee()
	$qBu : Parameter(paramCode == "QVTA_ALTAS_OP")
	$total : Summary(employee == $empleado && summaryCode == "ALTAS_VOZ")
	$totalBu : Summary(bu == $empleado.bu && summaryCode == "ALTAS_VOZ" && quantity >= $qBu.value)
	$p : Parameter(paramCode == "QVTA_ALTAS_VOZ_PU_ARS")
then
	Double performance = $total.getQuantity() * 100.0 / ($qBu.getValue() / $empleado.getBu().getEmployeeCount());
	if (performance >= $p.getMinValue()) {
		statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
				$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 31);
	}
end

/* ************ FIN INCENTIVOS INDIVIDUALES ************ */

/* ************ INCENTIVOS PUNTO DE VENTA ************** */
rule "Incentivos  Punto de Venta - X Altas Proporcional"
salience 70
when
	$empleado : Employee()
	$p : Parameter(paramCode == "IVTA_ALTAS_RG1_BON_ARS")
	$totalBu : Summary(bu == $empleado.bu && summaryCode == "ALTASYCATER" && quantity >= $p.minValue && quantity < $p.maxValue)
	$total : Summary(employee == $empleado && summaryCode == "ALTASYCATER")
then
	Double performance = $total.getQuantity() / $totalBu.getQuantity();
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
			$p.getValue(), performance * 100.0, $p.getValue() * performance, 10);
end

rule "Incentivos  Punto de Venta - XX Altas Proporcional"
salience 70
when
	$empleado : Employee()
	$p : Parameter(paramCode == "IVTA_ALTAS_RG2_BON_ARS")
	$totalBu : Summary(bu == $empleado.bu && summaryCode == "ALTASYCATER" && quantity >= $p.minValue)
	$total : Summary(employee == $empleado && summaryCode == "ALTASYCATER")
then
	Double performance = $total.getQuantity() / $totalBu.getQuantity();
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
			$p.getValue(), performance, $p.getValue() * performance, 11);
end

/* ********** FIN INCENTIVOS PUNTO DE VENTA  *********** */

/* ******************** DEDUCCIONES ******************** */
rule "Bajas - IM"
salience 60
when
	$empleado : Employee()
	$p : Parameter(paramCode == "BAJAS_IM_PU_ARS")
	$total : Summary(employee == $empleado && summaryCode == "IM_BAJAS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
			$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 10);
end

rule "Bajas - MEC"
salience 60
when
	$empleado : Employee()
	$p : Parameter(paramCode == "BAJAS_LEC_PU_ARS")
	$total : Summary(employee == $empleado && summaryCode == "LEC_BAJAS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
			$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 20);
end

rule "Bajas - Planes Interno/Externo"
salience 60
when
	$empleado : Employee()
	$p : Parameter(paramCode == "BAJA_PLAN_PU_ARS")
	$total : Summary(employee == $empleado && summaryCode == "PLAN_BAJAS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
			$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 30);
end

rule "Bajas - CDP a planes Full"
salience 60
when
	$empleado : Employee()
	$p : Parameter(paramCode == "BAJA_CPLANFULL_PU_ARS")
	$total : Summary(employee == $empleado && summaryCode == "FULL_BAJAS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
			$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 40);
end

rule "Bajas - Observaciones (Reclamos)"
salience 60
when
	$empleado : Employee()
	$p : Parameter(paramCode == "BAJA_RECLAMOS_PU_ARS")
	$total : Summary(employee == $empleado && summaryCode == "RECLAMOS")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
			$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 50);
end

rule "Bajas - Debitos por fraudes"
salience 60
when
	$empleado : Employee()
	$p : Parameter(paramCode == "BAJA_FRAUDES")
	$total : Summary(employee == $empleado && summaryCode == "FRAUDES")
then
	statement.addLine(StatementLineType.RULE, $p.getParamCategory(), $p.getCurrentDescription(), 
		$p.getValue(), $total.getQuantity(), $p.getValue() * $total.getQuantity(), 60);
end

rule "Bajas - Diferencias de precio"
salience 60
when
	$empleado : Employee()
	$total : Summary(employee == $empleado && summaryCode == "DIF_PRECIOS")
then
	statement.addLine(StatementLineType.RULE, StatementLineGroup.DEDUCTIONS, "Diferencias de precio", 
			null, null, $total.getQuantity(), 70);
end

/* ****************** FIN DEDUCCIONES ****************** */

/* ******************** REDONDEO *********************** */
/*rule "Redondeo"
salience 50
when
	$empleado: Employee()
then
	Double posSubtotal = statement.getStalesSubtotal() + statement.getIndIncentSubtotal() 
							+ statement.getPosIncentSubtotal();
	statement.setPositiveSubtotal(posSubtotal);
	Double balance = posSubtotal - statement.getDeductionsSubtotal();
	if (balance > 0.0D) {
		// TODO REDONDEO
		Double redondeo = 0.0D;
		statement.setTotal(balance + redondeo);
	} else if (balance < 0.0D) {
		statement.setDueBalance(balance);
		statement.setTotal(0.0D);
	}
end*/
/* ****************** FIN REDONDEO ********************* */
